//
// Created by Owner on 1/26/2026.
//

#ifndef TYPES_H
#define TYPES_H


enum QueryType {
    CIRCLE_ENGINE, PARABOLA_ENGINE, HYPERBOLA_ENGINE, ELLIPSE_ENGINE, GEOMETRY_ENGINE, UNKNOWN
};
enum EquationForm {
    STANDARD, GENERAL, VERTEX, FACTORED, POLAR, PARAMETRIC
};

#endif //TYPES_H
